version: "3.3"
services:
  miniob:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        miniob: ../
    image: miniob:latest
    container_name: miniob
    privileged: true
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    restart: unless-stopped
    volumes:
      - ../:/home/docker/miniob